### ISSUE TITLE
README needs example of running main playbook

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-deploy#113]
It is not obvious to a non-ansible friendly dev how the heck you're supposed to run the main playbook. Even under the section "Running the Main Playbook"

**Comment by pumazi** [comment]
There are a few things here I suppose...

It's no longer obvious, but cnx-deploy is not a developer tool any longer. The developer story has been dropped and with every change we move farther away from it. (IMHO, now having used ansible for over a year, it is not a good fit as a developer tool anyhow.)

The "Running the Main Playbook" section needs to be removed. This is especially the case because the contents of that section aren't about the main playbook but also because the issue it mentions should no longer exist. 🐛 

Depending on the environment, the main playbook may be different. For example, the `environments/local-accounts-vm` & `environments/legacy-staging` do not use the `main.yml` playbook. This is why the main README says to refer to the environment's `README.md` file for specific instructions.

With that said, I agree that the main README doesn't make it clear what one should do after installation. At least, no one section seems to illustrate next steps. So, I'll try to correct this. 😃
