### ISSUE TITLE
Failed to initialize the database's virtualenv with a non-localhost db hostname

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-deploy#145]
## Summary
```
Site error

If you were logged in, don't worry; you have not been logged out. Click the back button or one of the tabs to continue.

This site encountered an error trying to fulfill your request. The errors were:

Error Type
InternalError
Error Message
ImportError: No module named cnxarchive.database CONTEXT: Traceback (most recent call last): PL/Python function "assign_uuid_default", line 2, in <module> from cnxarchive.database import assign_document_controls_default_trigger PL/Python function "assign_uuid_default"
Request made at
2016/11/15 13:46:56.873 US/Central
```

Tried to publish a new module. Save worked (doesn't work when trying to save an existing module)

## Environment

http://legacy-dev00.cnx.org/

**Comment by pumazi** [comment]
Turns out we ran into an issue related to the database updating...

```
pumazi@dev00:/var/cnx/venvs/archive$ /var/cnx/venvs/archive/bin/cnx-db venv -h dev00.cnx.org -p 5432 -d repository -U rhaptos
/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxdb/init/main.py:106: UserWarning: An attempt to use ``init_venv`` was made, but not on the same host as the postgres service.
  warnings.warn("An attempt to use ``init_venv`` was made, "
```

I'm not sure this is a valid stopping point, but it does explain why the problem exists. Next action is to either remove that restriction in cnx-db or correct the play to always use 'localhost'. For now the fix might be to change the play to use 'localhost'. Then we will touch up this temporary fix in https://github.com/Connexions/cnx-deploy/milestone/3.

So, I'll fix the play as a temporary fix and I'll create an issue for our milestone.

**Comment by pumazi** [comment]
I've manually fixed the database since this is time sensitive. @helenemccarron please give it another try.

**Comment by helenemccarron** [comment]
`This item has been published.` This is working, thank you @pumazi

**Comment by pumazi** [comment]
Moved to phase three for where a complete fix will be worked on.

The complete fix is to ensure that the `cnx-db venv` command is run on the same server as the database.
