### ISSUE TITLE
Astronomy long generation time

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-deploy#219]
## Summary

Astronomy took less than 5 minutes to generate on Production: https://legacy.cnx.org/content/col11992/latest/query_ptool

Astronomy is taking over half an hour  to generate on staging.cnx.org: 
https://legacy-staging.cnx.org/content/col11992/latest/printinfo

Overall, most collections have a similar issue.

**Comment by DarkPrinceFrost** [comment]
Confirmed that this is indeed an issue. The staging server has more resources than the legacy server and _should_ perform equal-to or better-than the previous server

**Comment by reedstrm** [comment]
Note that apparent time from enqueue to pdf gen is affected by the med to build most of colcomplete, followed by building the pdf. If the pdfgen server is not configured to build mroe than one thing at a time, it will have to build _all_ of colcomplete, rather than most. This is much slower. I think @DarkPrinceFrost may have fixed that config late yesterday. It still needs to be coded into cnx-deploy, though so it is not a manual step.
